spring:
  application:
    name: employee
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb/${MONGO_DATABASE}
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

logging:
  pattern: 
    console: "%d{HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"